apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  namespace: vprofile
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: external-nginx
  rules:
    - host: vprofile.ochukowhoro.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vproweb-service
                port:
                  number: 80
  tls:
    - hosts:
        - vprofile.ochukowhoro.xyz
      secretName: vprofile-ochukowhoro-xyz
